version: "3.8"

services:
  simulador:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: simulador-app
    ports:
      - "8080:80"
    restart: unless-stopped

  simulador-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: simulador-app-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
